// https://j-brooke.github.io/FracturedJson/
// prettier-ignore
export const _2023 = {
  '2023': {
    'stationary_combustion': [
      {
        'state': 'solid',
        'unit': 'ton',
        'fuel_types': 'Coal And Coke',
        'name': 'Anthracite',
        'heat_content': 29.18,
        'CO2': 98.28,
        'CH4': 10,
        'N2O': 1.5,
        'id': 'solid-anthracite',
      },
      {
        'state': 'solid',
        'unit': 'ton',
        'fuel_types': 'Coal And Coke',
        'name': 'Bituminous',
        'heat_content': 28.99,
        'CO2': 88.41,
        'CH4': 10,
        'N2O': 1.5,
        'id': 'solid-bituminous',
      },
      {
        'state': 'solid',
        'unit': 'ton',
        'fuel_types': 'Coal And Coke',
        'name': 'Sub-bituminous',
        'heat_content': 20.06,
        'CO2': 92.1,
        'CH4': 10,
        'N2O': 1.5,
        'id': 'solid-sub-bituminous',
      },
      {
        'state': 'solid',
        'unit': 'ton',
        'fuel_types': 'Coal And Coke',
        'name': 'Lignite',
        'heat_content': 16.53,
        'CO2': 92.62,
        'CH4': 10,
        'N2O': 1.5,
        'id': 'solid-lignite',
      },
      {
        'state': 'solid',
        'unit': 'ton',
        'fuel_types': 'Coal And Coke',
        'name': 'Mixed (Commercial Sector)',
        'heat_content': 24.88,
        'CO2': 89.35,
        'CH4': 10,
        'N2O': 1.5,
        'id': 'solid-mixed-commercial-sector',
      },
      {
        'state': 'solid',
        'unit': 'ton',
        'fuel_types': 'Coal And Coke',
        'name': 'Mixed (Electric Power Sector)',
        'heat_content': 22.95,
        'CO2': 90.54,
        'CH4': 10,
        'N2O': 1.5,
        'id': 'solid-mixed-electric-power-sector',
      },
      {
        'state': 'solid',
        'unit': 'ton',
        'fuel_types': 'Coal And Coke',
        'name': 'Mixed (Industrial Coking)',
        'heat_content': 30.56,
        'CO2': 89,
        'CH4': 10,
        'N2O': 1.5,
        'id': 'solid-mixed-industrial-coking',
      },
      {
        'state': 'solid',
        'unit': 'ton',
        'fuel_types': 'Coal And Coke',
        'name': 'Mixed (Industrial Sector)',
        'heat_content': 25.99,
        'CO2': 89.73,
        'CH4': 10,
        'N2O': 1.5,
        'id': 'solid-mixed-industrial-sector',
      },
      {
        'state': 'solid',
        'unit': 'ton',
        'fuel_types': 'Coal And Coke',
        'name': 'Coal Coke',
        'heat_content': 28.84,
        'CO2': 107.74,
        'CH4': 10,
        'N2O': 1.5,
        'id': 'solid-coal-coke',
      },
      {
        'state': 'solid',
        'unit': 'ton',
        'fuel_types': 'Other Fuels',
        'name': 'Municipal Solid Waste',
        'heat_content': 13.46,
        'CO2': 85.97,
        'CH4': 30,
        'N2O': 4,
        'id': 'solid-municipal-solid-waste',
      },
      {
        'state': 'solid',
        'unit': 'ton',
        'fuel_types': 'Other Fuels',
        'name': 'Petroleum Coke (Solid)',
        'heat_content': 40.58,
        'CO2': 97.07,
        'CH4': 30,
        'N2O': 4,
        'id': 'solid-petroleum-coke-solid',
      },
      {
        'state': 'solid',
        'unit': 'ton',
        'fuel_types': 'Other Fuels',
        'name': 'Plastics',
        'heat_content': 51.4,
        'CO2': 71.09,
        'CH4': 30,
        'N2O': 4,
        'id': 'solid-plastics',
      },
      {
        'state': 'solid',
        'unit': 'ton',
        'fuel_types': 'Other Fuels',
        'name': 'Tires',
        'heat_content': 37.87,
        'CO2': 81.48,
        'CH4': 30,
        'N2O': 4,
        'id': 'solid-tires',
      },
      {
        'state': 'solid',
        'unit': 'ton',
        'fuel_types': 'Biomass Fuels',
        'name': 'Agricultural Byproducts',
        'heat_content': 15.65,
        'CO2': 112,
        'CH4': 30,
        'N2O': 4,
        'id': 'solid-agricultural-byproducts',
      },
      {
        'state': 'solid',
        'unit': 'ton',
        'fuel_types': 'Biomass Fuels',
        'name': 'Peat',
        'heat_content': 47.19,
        'CO2': 106,
        'CH4': 30,
        'N2O': 4,
        'id': 'solid-peat',
      },
      {
        'state': 'solid',
        'unit': 'ton',
        'fuel_types': 'Biomass Fuels',
        'name': 'Solid Byproducts',
        'heat_content': 59.78,
        'CO2': 100,
        'CH4': 30,
        'N2O': 4,
        'id': 'solid-solid-byproducts',
      },
      {
        'state': 'solid',
        'unit': 'ton',
        'fuel_types': 'Biomass Fuels',
        'name': 'Wood and Wood Residuals',
        'heat_content': 44.05,
        'CO2': 88.9,
        'CH4': 6.8,
        'N2O': 3.4,
        'id': 'solid-wood-and-wood-residuals',
      },
      {
        'state': 'gas',
        'unit': 'm3',
        'fuel_types': 'Natural Gas',
        'name': 'Natural Gas',
        'heat_content': 0.038228,
        'CO2': 50.29,
        'CH4': 0.9,
        'N2O': 0.09,
        'id': 'gas-natural-gas',
      },
      {
        'state': 'gas',
        'unit': 'm3',
        'fuel_types': 'Other Fuels',
        'name': 'Blast Furnace Gas',
        'heat_content': 0.003428,
        'CO2': 260,
        'CH4': 0.021,
        'N2O': 0.09,
        'id': 'gas-blast-furnace-gas',
      },
      {
        'state': 'gas',
        'unit': 'm3',
        'fuel_types': 'Other Fuels',
        'name': 'Coke Oven Gas',
        'heat_content': 0.022318,
        'CO2': 44.41,
        'CH4': 0.45,
        'N2O': 0.09,
        'id': 'gas-coke-oven-gas',
      },
      {
        'state': 'gas',
        'unit': 'm3',
        'fuel_types': 'Other Fuels',
        'name': 'Fuel Gas',
        'heat_content': 0.051716,
        'CO2': 55.92,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'gas-fuel-gas',
      },
      {
        'state': 'gas',
        'unit': 'm3',
        'fuel_types': 'Other Fuels',
        'name': 'Propane Gas',
        'heat_content': 0.093744,
        'CO2': 58.25,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'gas-propane-gas',
      },
      {
        'state': 'gas',
        'unit': 'm3',
        'fuel_types': 'Biomass Fuels',
        'name': 'Landfill Gas',
        'heat_content': 0.018071,
        'CO2': 49.35,
        'CH4': 3,
        'N2O': 0.6,
        'id': 'gas-landfill-gas',
      },
      {
        'state': 'gas',
        'unit': 'm3',
        'fuel_types': 'Biomass Fuels',
        'name': 'Other Biomass Gases',
        'heat_content': 0.024405,
        'CO2': 49.35,
        'CH4': 3,
        'N2O': 0.6,
        'id': 'gas-other-biomass-gases',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Asphalt and Road Oil',
        'heat_content': 44.04,
        'CO2': 71.43,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-asphalt-and-road-oil',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Aviation Gasoline',
        'heat_content': 33.45,
        'CO2': 65.64,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-aviation-gasoline',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Butane',
        'heat_content': 28.71,
        'CO2': 61.39,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-butane',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Butylene',
        'heat_content': 29.27,
        'CO2': 65.13,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-butylene',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Crude Oil',
        'heat_content': 38.46,
        'CO2': 70.65,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-crude-oil',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Distillate Fuel Oil No. 1',
        'heat_content': 38.74,
        'CO2': 69.43,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-distillate-fuel-oil-no-1',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Distillate Fuel Oil No. 2',
        'heat_content': 38.46,
        'CO2': 70.1,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-distillate-fuel-oil-no-2',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Distillate Fuel Oil No. 4',
        'heat_content': 40.69,
        'CO2': 71.12,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-distillate-fuel-oil-no-4',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Ethane',
        'heat_content': 18.95,
        'CO2': 56.49,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-ethane',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Ethylene',
        'heat_content': 16.17,
        'CO2': 62.52,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-ethylene',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Heavy Gas Oils',
        'heat_content': 41.25,
        'CO2': 71.01,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-heavy-gas-oils',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Isobutane',
        'heat_content': 27.59,
        'CO2': 61.55,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-isobutane',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Isobutylene',
        'heat_content': 28.71,
        'CO2': 65.27,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-isobutylene',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Kerosene',
        'heat_content': 37.63,
        'CO2': 71.28,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-kerosene',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Kerosene-Type Jet Fuel',
        'heat_content': 37.63,
        'CO2': 68.45,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-kerosene-type-jet-fuel',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Liquefied Petroleum Gases (LPG)',
        'heat_content': 25.64,
        'CO2': 58.49,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-liquefied-petroleum-gases-lpg',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Lubricants',
        'heat_content': 40.14,
        'CO2': 70.39,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-lubricants',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Motor Gasoline',
        'heat_content': 34.84,
        'CO2': 66.56,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-motor-gasoline',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Naphtha (<401 deg F)',
        'heat_content': 34.84,
        'CO2': 64.47,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-naphtha-401-deg-f',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Natural Gasoline',
        'heat_content': 30.66,
        'CO2': 63.39,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-natural-gasoline',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Other Oil (>401 deg F)',
        'heat_content': 38.74,
        'CO2': 72.24,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-other-oil-401-deg-f',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Pentanes Plus',
        'heat_content': 30.66,
        'CO2': 66.37,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-pentanes-plus',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Petrochemical Feedstocks',
        'heat_content': 34.84,
        'CO2': 67.31,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-petrochemical-feedstocks',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Propane',
        'heat_content': 25.36,
        'CO2': 59.59,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-propane',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Propylene',
        'heat_content': 25.36,
        'CO2': 64.23,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-propylene',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Residual Fuel Oil No. 5',
        'heat_content': 39.02,
        'CO2': 69.12,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-residual-fuel-oil-no-5',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Residual Fuel Oil No. 6',
        'heat_content': 41.81,
        'CO2': 71.18,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-residual-fuel-oil-no-6',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Special Naphtha',
        'heat_content': 34.84,
        'CO2': 68.56,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-special-naphtha',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Unfinished Oils',
        'heat_content': 38.74,
        'CO2': 70.65,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-unfinished-oils',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Petroleum Products',
        'name': 'Used Oil',
        'heat_content': 38.46,
        'CO2': 70.14,
        'CH4': 2.8,
        'N2O': 0.57,
        'id': 'liquid-used-oil',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Biomass Fuels',
        'name': 'Biodiesel (100%)',
        'heat_content': 35.676,
        'CO2': 69.99,
        'CH4': 1,
        'N2O': 0.1,
        'id': 'liquid-biodiesel-100',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Biomass Fuels',
        'name': 'Ethanol (100%)',
        'heat_content': 23.412,
        'CO2': 64.87,
        'CH4': 1,
        'N2O': 0.1,
        'id': 'liquid-ethanol-100',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Biomass Fuels',
        'name': 'Rendered Animal Fat',
        'heat_content': 34.84,
        'CO2': 67.35,
        'CH4': 1,
        'N2O': 0.1,
        'id': 'liquid-rendered-animal-fat',
      },
      {
        'state': 'liquid',
        'unit': 'm3',
        'fuel_types': 'Biomass Fuels',
        'name': 'Vegetable Oil',
        'heat_content': 33.446,
        'CO2': 77.29,
        'CH4': 1,
        'N2O': 0.1,
        'id': 'liquid-vegetable-oil',
      },
    ],
    'mobile_combustion': {
      'litre': [
        {
          'id': 'aviation-gasoline',
          'fuel_type': 'Aviation Gasoline',
          'CO2': 2.2,
          'CH4': 0,
          'N2O': 0,
        },
        {
          'id': 'biodiesel',
          'fuel_type': 'Biodiesel (100%)',
          'CO2': 2.5,
          'CH4': 0,
          'N2O': 0,
        },
        {
          'id': 'cng',
          'fuel_type': 'Compressed Natural Gas (CNG)',
          'CO2': 1.92,
          'CH4': 0,
          'N2O': 0,
        },
        {
          'id': 'diesel',
          'fuel_type': 'Diesel Fuel',
          'CO2': 2.7,
          'CH4': 0,
          'N2O': 0,
        },
        {
          'id': 'ethanol',
          'fuel_type': 'Ethanol (100%)',
          'CO2': 1.52,
          'CH4': 0,
          'N2O': 0,
        },
        {
          'id': 'aviation-kerosene',
          'fuel_type': 'Kerosene-Type Jet Fuel',
          'CO2': 2.58,
          'CH4': 0,
          'N2O': 0,
        },
        {
          'id': 'lng',
          'fuel_type': 'Liquefied Natural Gas (LNG)',
          'CO2': 1.19,
          'CH4': 0,
          'N2O': 0,
        },
        {
          'id': 'lpg',
          'fuel_type': 'Liquefied Petroleum Gases (LPG)',
          'CO2': 1.5,
          'CH4': 0,
          'N2O': 0,
        },
        {
          'id': 'motor-gasoline',
          'fuel_type': 'Motor Gasoline',
          'CO2': 2.32,
          'CH4': 0,
          'N2O': 0,
        },
        {
          'id': 'residual-fuel-oil',
          'fuel_type': 'Residual Fuel Oil',
          'CO2': 2.98,
          'CH4': 0,
          'N2O': 0,
        },
      ],
      'distance': [{
        'vehicle_type': 'Passenger Cars',
        'fuel_type': 'Gasoline',
        'CO2': 0,
        'CH4': 0.0031,
        'N2O': 0.0009,
        'litreId': 'motor-gasoline',
        'id': 'passenger-cars-gasoline',
      }, {
        'vehicle_type': 'Passenger Cars',
        'fuel_type': 'Diesel',
        'CO2': 0,
        'CH4': 0.0188,
        'N2O': 0.0119,
        'litreId': 'diesel',
        'id': 'passenger-cars-diesel',
      }, {
        'vehicle_type': 'Passenger Cars',
        'fuel_type': 'Methanol',
        'CO2': 0,
        'CH4': 0.0081,
        'N2O': 0.0025,
        'litreId': '',
        'id': 'passenger-cars-methanol',
      }, {
        'vehicle_type': 'Passenger Cars',
        'fuel_type': 'Ethanol',
        'CO2': 0,
        'CH4': 0.0081,
        'N2O': 0.0025,
        'litreId': 'ethanol',
        'id': 'passenger-cars-ethanol',
      }, {
        'vehicle_type': 'Passenger Cars',
        'fuel_type': 'CNG',
        'CO2': 0,
        'CH4': 0.0826,
        'N2O': 0.0025,
        'litreId': 'cng',
        'id': 'passenger-cars-cng',
      }, {
        'vehicle_type': 'Passenger Cars',
        'fuel_type': 'LPG',
        'CO2': 0,
        'CH4': 0.0081,
        'N2O': 0.0025,
        'litreId': 'lpg',
        'id': 'passenger-cars-lpg',
      }, {
        'vehicle_type': 'Passenger Cars',
        'fuel_type': 'Biodiesel',
        'CO2': 0,
        'CH4': 0.0224,
        'N2O': 0.0006,
        'litreId': 'biodiesel',
        'id': 'passenger-cars-biodiesel',
      }, {
        'vehicle_type': 'Light-Duty Trucks',
        'fuel_type': 'Gasoline',
        'CO2': 0,
        'CH4': 0.0049,
        'N2O': 0.0007,
        'litreId': 'motor-gasoline',
        'id': 'light-duty-trucks-gasoline',
      }, {
        'vehicle_type': 'Light-Duty Trucks',
        'fuel_type': 'Diesel',
        'CO2': 0,
        'CH4': 0.018,
        'N2O': 0.0133,
        'litreId': 'diesel',
        'id': 'light-duty-trucks-diesel',
      }, {
        'vehicle_type': 'Light-Duty Trucks',
        'fuel_type': 'Ethanol',
        'CO2': 0,
        'CH4': 0.0087,
        'N2O': 0.0031,
        'litreId': 'ethanol',
        'id': 'light-duty-trucks-ethanol',
      }, {
        'vehicle_type': 'Light-Duty Trucks',
        'fuel_type': 'CNG',
        'CO2': 0,
        'CH4': 0.0895,
        'N2O': 0.0031,
        'litreId': 'cng',
        'id': 'light-duty-trucks-cng',
      }, {
        'vehicle_type': 'Light-Duty Trucks',
        'fuel_type': 'LPG',
        'CO2': 0,
        'CH4': 0.0087,
        'N2O': 0.0031,
        'litreId': 'lpg',
        'id': 'light-duty-trucks-lpg',
      }, {
        'vehicle_type': 'Light-Duty Trucks',
        'fuel_type': 'LNG',
        'CO2': 0,
        'CH4': 0.0895,
        'N2O': 0.0031,
        'litreId': 'lng',
        'id': 'light-duty-trucks-lng',
      }, {
        'vehicle_type': 'Light-Duty Trucks',
        'fuel_type': 'Biodiesel',
        'CO2': 0,
        'CH4': 0.0789,
        'N2O': 0.0006,
        'litreId': 'biodiesel',
        'id': 'light-duty-trucks-biodiesel',
      }, {
        'vehicle_type': 'Heavy-Duty Vehicles',
        'fuel_type': 'Gasoline',
        'CO2': 0,
        'CH4': 0.0206,
        'N2O': 0.0062,
        'litreId': 'motor-gasoline',
        'id': 'heavy-duty-vehicles-gasoline',
      }, {
        'vehicle_type': 'Heavy-Duty Vehicles',
        'fuel_type': 'Diesel',
        'CO2': 0,
        'CH4': 0.0059,
        'N2O': 0.0268,
        'litreId': 'diesel',
        'id': 'heavy-duty-vehicles-diesel',
      }, {
        'vehicle_type': 'Heavy-Duty Vehicles',
        'fuel_type': 'Methanol',
        'CO2': 0,
        'CH4': 0.0454,
        'N2O': 0.0168,
        'litreId': '',
        'id': 'heavy-duty-vehicles-methanol',
      }, {
        'vehicle_type': 'Heavy-Duty Vehicles',
        'fuel_type': 'Ethanol',
        'CO2': 0,
        'CH4': 0.0454,
        'N2O': 0.0168,
        'litreId': 'ethanol',
        'id': 'heavy-duty-vehicles-ethanol',
      }, {
        'vehicle_type': 'Heavy-Duty Vehicles',
        'fuel_type': 'CNG',
        'CO2': 0,
        'CH4': 0.5723,
        'N2O': 0.0106,
        'litreId': 'cng',
        'id': 'heavy-duty-vehicles-cng',
      }, {
        'vehicle_type': 'Heavy-Duty Vehicles',
        'fuel_type': 'LPG',
        'CO2': 0,
        'CH4': 0.0572,
        'N2O': 0.0106,
        'litreId': 'lpg',
        'id': 'heavy-duty-vehicles-lpg',
      }, {
        'vehicle_type': 'Heavy-Duty Vehicles',
        'fuel_type': 'LNG',
        'CO2': 0,
        'CH4': 0.5723,
        'N2O': 0.0106,
        'litreId': 'lng',
        'id': 'heavy-duty-vehicles-lng',
      }, {
        'vehicle_type': 'Heavy-Duty Vehicles',
        'fuel_type': 'Biodiesel',
        'CO2': 0,
        'CH4': 0.0087,
        'N2O': 0.0012,
        'litreId': 'biodiesel',
        'id': 'heavy-duty-vehicles-biodiesel',
      }, {
        'vehicle_type': 'Buses',
        'fuel_type': 'Methanol',
        'CO2': 0,
        'CH4': 0.1199,
        'N2O': 0.018,
        'litreId': '',
        'id': 'buses-methanol',
      }, {
        'vehicle_type': 'Buses',
        'fuel_type': 'Ethanol',
        'CO2': 0,
        'CH4': 0.1199,
        'N2O': 0.018,
        'litreId': 'ethanol',
        'id': 'buses-ethanol',
      }, {
        'vehicle_type': 'Buses',
        'fuel_type': 'CNG',
        'CO2': 0,
        'CH4': 1.7106,
        'N2O': 0.0106,
        'litreId': 'cng',
        'id': 'buses-cng',
      }, {
        'vehicle_type': 'Buses',
        'fuel_type': 'LPG',
        'CO2': 0,
        'CH4': 0.1709,
        'N2O': 0.0106,
        'litreId': 'lpg',
        'id': 'buses-lpg',
      }, {
        'vehicle_type': 'Buses',
        'fuel_type': 'LNG',
        'CO2': 0,
        'CH4': 1.7106,
        'N2O': 0.0106,
        'litreId': 'lng',
        'id': 'buses-lng',
      }, {
        'vehicle_type': 'Buses',
        'fuel_type': 'Biodiesel',
        'CO2': 0,
        'CH4': 0.0099,
        'N2O': 0.0019,
        'litreId': 'biodiesel',
        'id': 'buses-biodiesel',
      }, {
        'vehicle_type': 'Motorcycles',
        'fuel_type': 'Gasoline',
        'CO2': 0,
        'CH4': 0.0043,
        'N2O': 0.0052,
        'litreId': 'motor-gasoline',
        'id': 'motorcycles-gasoline',
      }, {
        'vehicle_type': 'Ships and Boats',
        'fuel_type': 'Residual Fuel Oil',
        'CO2': 0,
        'CH4': 0.69,
        'N2O': 0.2,
        'litreId': 'residual-fuel-oil',
        'id': 'ships-and-boats-residual-fuel-oil',
      }, {
        'vehicle_type': 'Ships and Boats',
        'fuel_type': 'Gasoline (2 stroke)',
        'CO2': 0,
        'CH4': 2.88,
        'N2O': 0.05,
        'litreId': '',
        'id': 'ships-and-boats-gasoline-2-stroke',
      }, {
        'vehicle_type': 'Ships and Boats',
        'fuel_type': 'Gasoline (4 stroke)',
        'CO2': 0,
        'CH4': 1.4,
        'N2O': 0.01,
        'litreId': '',
        'id': 'ships-and-boats-gasoline-4-stroke',
      }, {
        'vehicle_type': 'Ships and Boats',
        'fuel_type': 'Diesel',
        'CO2': 0,
        'CH4': 3.98,
        'N2O': 0.11,
        'litreId': 'diesel',
        'id': 'ships-and-boats-diesel',
      }, {
        'vehicle_type': 'Train',
        'fuel_type': 'Diesel',
        'CO2': 0,
        'CH4': 0.5,
        'N2O': 0.16,
        'litreId': 'diesel',
        'id': 'train-diesel',
      }, {
        'vehicle_type': 'Aircraft',
        'fuel_type': 'Jet Fuel',
        'CO2': 0,
        'CH4': 0,
        'N2O': 0.19,
        'litreId': 'aviation-kerosene',
        'id': 'aircraft-jet-fuel',
      }, {
        'vehicle_type': 'Aircraft',
        'fuel_type': 'Aviation Gasoline',
        'CO2': 0,
        'CH4': 4.39,
        'N2O': 0.07,
        'litreId': 'aviation-gasoline',
        'id': 'aircraft-aviation-gasoline',
      }],
    },
    'scope2': {
      'electric': {
        'peninsular': 0.758,
        'sabah': 0.425,
        'sarawak': 0.198,
        'unit': '(kg CO2e / kWh)',
      },
      'steam': { 'CO2': 62.87, 'CH4': 1.185, 'N2O': 0.118 },
      'cooling': { 'CO2': 62.87, 'CH4': 1.185, 'N2O': 0.118 },
      'heat': { 'CO2': 62.87, 'CH4': 1.185, 'N2O': 0.118 },
    },
    'GWP': [
      {
        'id': 'carbon-dioxide',
        'name': 'Carbon dioxide',
        'symbol': 'CO2',
        'value': 1,
      },
      {
        'id': 'methane',
        'name': 'Methane',
        'symbol': 'CH4',
        'value': 28,
      },
      {
        'id': 'nitrous-oxide',
        'name': 'Nitrous oxide',
        'symbol': 'N2O',
        'value': 265,
      },
      {
        'id': 'hfc-23',
        'name': 'HFC-23',
        'symbol': 'CHF3',
        'value': 12400,
      },
      {
        'id': 'hfc-32',
        'name': 'HFC-32',
        'symbol': 'CH2F2',
        'value': 677,
      },
      {
        'id': 'hfc-41',
        'name': 'HFC-41',
        'symbol': 'CH3F',
        'value': 116,
      },
      {
        'id': 'hfc-125',
        'name': 'HFC-125',
        'symbol': 'CHF2CF3',
        'value': 3170,
      },
      {
        'id': 'hfc-134',
        'name': 'HFC-134',
        'symbol': 'CHF2CHF2',
        'value': 1120,
      },
      {
        'id': 'hfc-134-a',
        'name': 'HFC-134a',
        'symbol': 'CH2FCF3',
        'value': 1300,
      },
      {
        'id': 'hfc-143',
        'name': 'HFC-143',
        'symbol': 'CH2FCHF2',
        'value': 328,
      },
      {
        'id': 'hfc-143-a',
        'name': 'HFC-143a',
        'symbol': 'CH3CF3',
        'value': 4800,
      },
      {
        'id': 'hfc-152',
        'name': 'HFC-152',
        'symbol': 'CH2FCH2F',
        'value': 16,
      },
      {
        'id': 'hfc-152-a',
        'name': 'HFC-152a',
        'symbol': 'CH3CHF2',
        'value': 138,
      },
      {
        'id': 'hfc-161',
        'name': 'HFC-161',
        'symbol': 'CH3CH2F',
        'value': 4,
      },
      {
        'id': 'hfc-227-ea',
        'name': 'HFC-227ea',
        'symbol': 'CF3CHFCF3',
        'value': 3350,
      },
      {
        'id': 'hfc-236-cb',
        'name': 'HFC-236cb',
        'symbol': 'CH2FCF2CF3',
        'value': 1210,
      },
      {
        'id': 'hfc-236-ea',
        'name': 'HFC-236ea',
        'symbol': 'CHF2CHFCF3',
        'value': 1330,
      },
      {
        'id': 'hfc-236-fa',
        'name': 'HFC-236fa',
        'symbol': 'CF3CH2CF3',
        'value': 8060,
      },
      {
        'id': 'hfc-245-ca',
        'name': 'HFC-245ca',
        'symbol': 'CH2FCF2CHF2',
        'value': 716,
      },
      {
        'id': 'hfc-245-fa',
        'name': 'HFC-245fa',
        'symbol': 'CHF2CH2CF3',
        'value': 858,
      },
      {
        'id': 'hfc-365-mfc',
        'name': 'HFC-365mfc',
        'symbol': 'CH3CF2CH2CF3',
        'value': 804,
      },
      {
        'id': 'hfc-43-10-mee',
        'name': 'HFC-43-10mee',
        'symbol': 'CF3CHFCHFCF2CF3',
        'value': 1650,
      },
      {
        'id': 'sulfur-hexafluoride',
        'name': 'Sulfur hexafluoride',
        'symbol': 'SF6',
        'value': 23500,
      },
      {
        'id': 'nitrogen-trifluoride',
        'name': 'Nitrogen trifluoride',
        'symbol': 'NF3',
        'value': 16100,
      },
      {
        'id': 'pfc-14',
        'name': 'PFC-14',
        'symbol': 'CF4',
        'value': 6630,
      },
      {
        'id': 'pfc-116',
        'name': 'PFC-116',
        'symbol': 'C2F6',
        'value': 11100,
      },
      {
        'id': 'pfc-218',
        'name': 'PFC-218',
        'symbol': 'C3F8',
        'value': 8900,
      },
      {
        'id': 'pfc-318',
        'name': 'PFC-318',
        'symbol': 'c-C4F8',
        'value': 9540,
      },
      {
        'id': 'pfc-31-10',
        'name': 'PFC-31-10',
        'symbol': 'C4F10',
        'value': 9200,
      },
      {
        'id': 'pfc-41-12',
        'name': 'PFC-41-12',
        'symbol': 'C5F12',
        'value': 8550,
      },
      {
        'id': 'pfc-51-14',
        'name': 'PFC-51-14',
        'symbol': 'C6F14',
        'value': 7910,
      },
      {
        'id': 'pfc-91-18',
        'name': 'PFC-91-18',
        'symbol': 'C10F18',
        'value': 7190,
      },
    ],
    'waste_generated': [
      {
        'id': 'aluminum-cans',
        'material': 'Aluminum Cans',
        'recycled': 0.07,
        'landfilled': 0.02,
        'combusted': 0.01,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'aluminum-ingot',
        'material': 'Aluminum Ingot',
        'recycled': 0.04,
        'landfilled': 0.02,
        'combusted': 0.01,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'steel-cans',
        'material': 'Steel Cans',
        'recycled': 0.35,
        'landfilled': 0.02,
        'combusted': 0.01,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'copper-wire',
        'material': 'Copper Wire',
        'recycled': 0.2,
        'landfilled': 0.02,
        'combusted': 0.01,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'glass',
        'material': 'Glass',
        'recycled': 0.06,
        'landfilled': 0.02,
        'combusted': 0.01,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'hdpe',
        'material': 'HDPE',
        'recycled': 0.23,
        'landfilled': 0.02,
        'combusted': 3.09,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'ldpe',
        'material': 'LDPE',
        'recycled': null,
        'landfilled': 0.02,
        'combusted': 3.09,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'pet',
        'material': 'PET',
        'recycled': 0.25,
        'landfilled': 0.02,
        'combusted': 2.26,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'lldpe',
        'material': 'LLDPE',
        'recycled': null,
        'landfilled': 0.02,
        'combusted': 3.09,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'pp',
        'material': 'PP',
        'recycled': 0.22,
        'landfilled': 0.02,
        'combusted': 3.09,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'ps',
        'material': 'PS',
        'recycled': null,
        'landfilled': 0.02,
        'combusted': 3.33,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'pvc',
        'material': 'PVC',
        'recycled': null,
        'landfilled': 0.02,
        'combusted': 1.39,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'pla',
        'material': 'PLA',
        'recycled': null,
        'landfilled': 0.02,
        'combusted': 0.01,
        'composted': 0.14,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'corrugated-containers',
        'material': 'Corrugated Containers',
        'recycled': 0.12,
        'landfilled': 1.1,
        'combusted': 0.06,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'magazines-third-class-mail',
        'material': 'Magazines/Third-class mail',
        'recycled': 0.02,
        'landfilled': 0.51,
        'combusted': 0.06,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'newspaper',
        'material': 'Newspaper',
        'recycled': 0.02,
        'landfilled': 0.43,
        'combusted': 0.06,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'office-paper',
        'material': 'Office Paper',
        'recycled': 0.02,
        'landfilled': 1.55,
        'combusted': 0.06,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'phonebooks',
        'material': 'Phonebooks',
        'recycled': 0.04,
        'landfilled': 0.43,
        'combusted': 0.06,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'textbooks',
        'material': 'Textbooks',
        'recycled': 0.04,
        'landfilled': 1.55,
        'combusted': 0.06,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'dimensional-lumber',
        'material': 'Dimensional Lumber',
        'recycled': null,
        'landfilled': 0.19,
        'combusted': 0.06,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'medium-density-fiberboard',
        'material': 'Medium-density Fiberboard',
        'recycled': null,
        'landfilled': 0.08,
        'combusted': 0.06,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'food-waste-non-meat',
        'material': 'Food Waste (non-meat)',
        'recycled': null,
        'landfilled': 0.74,
        'combusted': 0.06,
        'composted': 0.12,
        'anaerobically_digested_dry': 0.15,
        'anaerobically_digested_wet': 0.12,
      },
      {
        'id': 'food-waste-meat-only',
        'material': 'Food Waste (meat only)',
        'recycled': null,
        'landfilled': 0.76,
        'combusted': 0.06,
        'composted': 0.12,
        'anaerobically_digested_dry': 0.15,
        'anaerobically_digested_wet': 0.12,
      },
      {
        'id': 'beef',
        'material': 'Beef',
        'recycled': null,
        'landfilled': 0.71,
        'combusted': 0.06,
        'composted': 0.12,
        'anaerobically_digested_dry': 0.15,
        'anaerobically_digested_wet': 0.12,
      },
      {
        'id': 'poultry',
        'material': 'Poultry',
        'recycled': null,
        'landfilled': 0.8,
        'combusted': 0.06,
        'composted': 0.12,
        'anaerobically_digested_dry': 0.15,
        'anaerobically_digested_wet': 0.12,
      },
      {
        'id': 'grains',
        'material': 'Grains',
        'recycled': null,
        'landfilled': 2.27,
        'combusted': 0.06,
        'composted': 0.12,
        'anaerobically_digested_dry': 0.15,
        'anaerobically_digested_wet': 0.12,
      },
      {
        'id': 'bread',
        'material': 'Bread',
        'recycled': null,
        'landfilled': 1.64,
        'combusted': 0.06,
        'composted': 0.12,
        'anaerobically_digested_dry': 0.15,
        'anaerobically_digested_wet': 0.12,
      },
      {
        'id': 'fruits-and-vegetables',
        'material': 'Fruits and Vegetables',
        'recycled': null,
        'landfilled': 0.31,
        'combusted': 0.06,
        'composted': 0.12,
        'anaerobically_digested_dry': 0.15,
        'anaerobically_digested_wet': 0.12,
      },
      {
        'id': 'dairy-products',
        'material': 'Dairy Products',
        'recycled': null,
        'landfilled': 0.79,
        'combusted': 0.06,
        'composted': 0.12,
        'anaerobically_digested_dry': 0.15,
        'anaerobically_digested_wet': 0.12,
      },
      {
        'id': 'yard-trimmings',
        'material': 'Yard Trimmings',
        'recycled': null,
        'landfilled': 0.4,
        'combusted': 0.06,
        'composted': 0.15,
        'anaerobically_digested_dry': 0.12,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'grass',
        'material': 'Grass',
        'recycled': null,
        'landfilled': 0.31,
        'combusted': 0.06,
        'composted': 0.15,
        'anaerobically_digested_dry': 0.1,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'leaves',
        'material': 'Leaves',
        'recycled': null,
        'landfilled': 0.31,
        'combusted': 0.06,
        'composted': 0.15,
        'anaerobically_digested_dry': 0.13,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'branches',
        'material': 'Branches',
        'recycled': null,
        'landfilled': 0.64,
        'combusted': 0.06,
        'composted': 0.15,
        'anaerobically_digested_dry': 0.17,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'mixed-paper-general',
        'material': 'Mixed Paper (general)',
        'recycled': 0.08,
        'landfilled': 0.98,
        'combusted': 0.06,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'mixed-paper-primarily-residential',
        'material': 'Mixed Paper (primarily residential)',
        'recycled': 0.08,
        'landfilled': 0.95,
        'combusted': 0.06,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'mixed-paper-primarily-from-offices',
        'material': 'Mixed Paper (primarily from offices)',
        'recycled': 0.03,
        'landfilled': 0.93,
        'combusted': 0.06,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'mixed-metals',
        'material': 'Mixed Metals',
        'recycled': 0.25,
        'landfilled': 0.02,
        'combusted': 0.01,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'mixed-plastics',
        'material': 'Mixed Plastics',
        'recycled': 0.24,
        'landfilled': 0.02,
        'combusted': 2.58,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'mixed-recyclables',
        'material': 'Mixed Recyclables',
        'recycled': 0.1,
        'landfilled': 0.83,
        'combusted': 0.12,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'food-waste',
        'material': 'Food Waste',
        'recycled': null,
        'landfilled': 0.75,
        'combusted': 0.06,
        'composted': 0.12,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'mixed-organics',
        'material': 'Mixed Organics',
        'recycled': null,
        'landfilled': 0.6,
        'combusted': 0.06,
        'composted': 0.14,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'mixed-msw',
        'material': 'Mixed MSW',
        'recycled': null,
        'landfilled': 0.64,
        'combusted': 0.47,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'carpet',
        'material': 'Carpet',
        'recycled': null,
        'landfilled': 0.02,
        'combusted': 1.85,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'desktop-cp-us',
        'material': 'Desktop CPUs',
        'recycled': 0.01,
        'landfilled': 0.02,
        'combusted': 0.44,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'portable-electronic-devices',
        'material': 'Portable Electronic Devices',
        'recycled': 0.02,
        'landfilled': 0.02,
        'combusted': 0.98,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'flat-panel-displays',
        'material': 'Flat-panel Displays',
        'recycled': 0.02,
        'landfilled': 0.02,
        'combusted': 0.82,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'crt-displays',
        'material': 'CRT Displays',
        'recycled': null,
        'landfilled': 0.02,
        'combusted': 0.71,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'electronic-peripherals',
        'material': 'Electronic Peripherals',
        'recycled': 0.06,
        'landfilled': 0.02,
        'combusted': 2.46,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'hard-copy-devices',
        'material': 'Hard-copy Devices',
        'recycled': 0.01,
        'landfilled': 0.02,
        'combusted': 2.12,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'mixed-electronics',
        'material': 'Mixed Electronics',
        'recycled': 0.02,
        'landfilled': 0.02,
        'combusted': 1.06,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'clay-bricks',
        'material': 'Clay Bricks',
        'recycled': null,
        'landfilled': 0.02,
        'combusted': null,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'concrete',
        'material': 'Concrete',
        'recycled': 0.01,
        'landfilled': 0.02,
        'combusted': null,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'fly-ash',
        'material': 'Fly Ash',
        'recycled': 0.01,
        'landfilled': 0.02,
        'combusted': null,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'tires',
        'material': 'Tires',
        'recycled': 0.11,
        'landfilled': 0.02,
        'combusted': 2.44,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'asphalt-concrete',
        'material': 'Asphalt Concrete',
        'recycled': 0,
        'landfilled': 0.02,
        'combusted': null,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'asphalt-shingles',
        'material': 'Asphalt Shingles',
        'recycled': 0.03,
        'landfilled': 0.02,
        'combusted': 0.77,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'drywall',
        'material': 'Drywall',
        'recycled': null,
        'landfilled': 0.02,
        'combusted': null,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'fiberglass-insulation',
        'material': 'Fiberglass Insulation',
        'recycled': 0.06,
        'landfilled': 0.02,
        'combusted': null,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'structural-steel',
        'material': 'Structural Steel',
        'recycled': 0.04,
        'landfilled': 0.02,
        'combusted': null,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'vinyl-flooring',
        'material': 'Vinyl Flooring',
        'recycled': null,
        'landfilled': 0.02,
        'combusted': 0.32,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
      {
        'id': 'wood-flooring',
        'material': 'Wood Flooring',
        'recycled': null,
        'landfilled': 0.2,
        'combusted': 0.09,
        'composted': null,
        'anaerobically_digested_dry': null,
        'anaerobically_digested_wet': null,
      },
    ],
    waste_generated_supplier_specific_method: [
      { id: 'wmc_treated_waste', name: 'WMC treated waste', value: 0.448 },
      { id: 'thermal_treatment_of_incinerable_waste', name: 'Thermal treatment of incinerable', value: 1.459 },
      { id: 'secured_landfill_of_inert_wastes', name: 'Secured landfill of incinerable', value: 0.081 },
      { id: 'solidification_of_inorganic_wastes', name: 'Solidification of inorganic wastes', value: 0.278 },
      { id: 'physical_chemical_treatment_of_liquid_wastes', name: 'Physical Chemical Chemical Chemical', value: 0.223 },
      { id: 'all_crr_output', name: 'All CRR Output', value: 0.095 },
    ],
  },
}
